### ISSUE TITLE
Input while hook is blocking mouse

### ISSUE THREAD

**Issue by msalai** [DavidRieman/SimWinInput#4]
I wonder if it is somehow possible to send mouse inputs while mouse hook is preventing mouse usage?

**Comment by DavidRieman** [comment]
Could you elaborate on the problem / reproduction scenario?
(SimWinMouse essentially provides a user-friendly way to work with [mouse_event](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-mouse_event) interop calls - if it can do what you need, perhaps an API change could expose this to others with similar needs.)

**Comment by msalai** [comment]
I am making remote control application so that computer A can control computer B, but I wish to prevent user on computer B to use his mouse. Only person on computer A needs to be able to control mouse on computer B. So I am using mouse hooks to block mouse input, but is there a way to somehow send input anyway from program only?

**Comment by DavidRieman** [comment]
Sorry, my API won't be able to help with that.
