### ISSUE TITLE
Anti-cheat disable keyboard

### ISSUE THREAD

**Issue by ateo** [DavidRieman/SimWinInput#5]
Dear Author
I try your lib but do not work with Anti-cheat disable all keyboard virtual, tabtip.exe do not work
How can bypass to using press key.
idea: make diver virtual keyboard, and SimWinInput execute via it

**Comment by DavidRieman** [comment]
I'm not sure I understand your reproduction scenario, but it sounds like SimWinKeyboard might not be the tool for the job.  Ultimately I do not wish to build or host a custom driver for it, so if you go that route, you may wish to just build and host your own code in another repo.  Depending on your scenario, I may have other ideas for you though.
